/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(new URL('smb-js.android-arm64.node', import.meta.url))
        try {
          if (localFileExisted) {
            nativeBinding = require(new URL('smb-js.android-arm64.node', import.meta.url).pathname)
          } else {
            nativeBinding = require('@netapplabs/smb-js-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(new URL('smb-js.android-arm-eabi.node', import.meta.url))
        try {
          if (localFileExisted) {
            nativeBinding = require(new URL('smb-js.android-arm-eabi.node', import.meta.url).pathname)
          } else {
            nativeBinding = require('@netapplabs/smb-js-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(new URL('smb-js.win32-x64-msvc.node', import.meta.url))
        try {
          if (localFileExisted) {
            nativeBinding = require(new URL('smb-js.win32-x64-msvc.node', import.meta.url).pathname)
          } else {
            nativeBinding = require('@netapplabs/smb-js-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(new URL('smb-js.win32-ia32-msvc.node', import.meta.url))
        try {
          if (localFileExisted) {
            nativeBinding = require(new URL('smb-js.win32-ia32-msvc.node', import.meta.url).pathname)
          } else {
            nativeBinding = require('@netapplabs/smb-js-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(new URL('smb-js.win32-arm64-msvc.node', import.meta.url))
        try {
          if (localFileExisted) {
            nativeBinding = require(new URL('smb-js.win32-arm64-msvc.node', import.meta.url).pathname)
          } else {
            nativeBinding = require('@netapplabs/smb-js-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    try {
      if (localFileExisted) {
      } else {
        nativeBinding = require('@netapplabs/smb-js-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(new URL('smb-js.darwin-x64.node', import.meta.url))
        try {
          if (localFileExisted) {
            nativeBinding = require(new URL('smb-js.darwin-x64.node', import.meta.url).pathname)
          } else {
            nativeBinding = require('@netapplabs/smb-js-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(new URL('smb-js.darwin-arm64.node', import.meta.url))
        try {
          if (localFileExisted) {
            nativeBinding = require(new URL('smb-js.darwin-arm64.node', import.meta.url).pathname)
          } else {
            nativeBinding = require('@netapplabs/smb-js-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(new URL('smb-js.freebsd-x64.node', import.meta.url))
    try {
      if (localFileExisted) {
        nativeBinding = require(new URL('smb-js.freebsd-x64.node', import.meta.url).pathname)
      } else {
        nativeBinding = require('@netapplabs/smb-js-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(new URL('smb-js.linux-x64-musl.node', import.meta.url))
          try {
            if (localFileExisted) {
              nativeBinding = require(new URL('smb-js.linux-x64-musl.node', import.meta.url).pathname)
            } else {
              nativeBinding = require('@netapplabs/smb-js-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(new URL('smb-js.linux-x64-gnu.node', import.meta.url))
          try {
            if (localFileExisted) {
              nativeBinding = require(new URL('smb-js.linux-x64-gnu.node', import.meta.url).pathname)
            } else {
              nativeBinding = require('@netapplabs/smb-js-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(new URL('smb-js.linux-arm64-musl.node', import.meta.url))
          try {
            if (localFileExisted) {
              nativeBinding = require(new URL('smb-js.linux-arm64-musl.node', import.meta.url).pathname)
            } else {
              nativeBinding = require('@netapplabs/smb-js-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(new URL('smb-js.linux-arm64-gnu.node', import.meta.url))
          try {
            if (localFileExisted) {
              nativeBinding = require(new URL('smb-js.linux-arm64-gnu.node', import.meta.url).pathname)
            } else {
              nativeBinding = require('@netapplabs/smb-js-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(new URL('smb-js.linux-arm-musleabihf.node', import.meta.url))
          try {
            if (localFileExisted) {
              nativeBinding = require(new URL('smb-js.linux-arm-musleabihf.node', import.meta.url).pathname)
            } else {
              nativeBinding = require('@netapplabs/smb-js-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(new URL('smb-js.linux-arm-gnueabihf.node', import.meta.url))
          try {
            if (localFileExisted) {
              nativeBinding = require(new URL('smb-js.linux-arm-gnueabihf.node', import.meta.url).pathname)
            } else {
              nativeBinding = require('@netapplabs/smb-js-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(new URL('smb-js.linux-riscv64-musl.node', import.meta.url))
          try {
            if (localFileExisted) {
              nativeBinding = require(new URL('smb-js.linux-riscv64-musl.node', import.meta.url).pathname)
            } else {
              nativeBinding = require('@netapplabs/smb-js-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(new URL('smb-js.linux-riscv64-gnu.node', import.meta.url))
          try {
            if (localFileExisted) {
              nativeBinding = require(new URL('smb-js.linux-riscv64-gnu.node', import.meta.url).pathname)
            } else {
              nativeBinding = require('@netapplabs/smb-js-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(new URL('smb-js.linux-s390x-gnu.node', import.meta.url))
        try {
          if (localFileExisted) {
            nativeBinding = require(new URL('smb-js.linux-s390x-gnu.node', import.meta.url).pathname)
          } else {
            nativeBinding = require('@netapplabs/smb-js-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

export const {
  JsSmbDirectoryHandleEntries,
  JsSmbDirectoryHandleKeys,
  JsSmbDirectoryHandleValues,
  JsSmbHandle,
  JsSmbDirectoryHandle,
  Cancellable,
  JsSmbFileHandle,
  JsSmbFile,
  JsSmbReadableStreamSource,
  JsSmbWritableFileStream,
  JsSmbWritableStreamSink,
} = nativeBinding

