# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main", "npm" ]
  pull_request:
    branches: [ "main" , "npm" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  adeps-linux:
    runs-on: [ubuntu-24.04]
    steps:
    - name: Install samba
      run: sudo apt-get -y install samba libc6-dev-amd64-cross libc6-dev-arm64-cross
  adeps-macos:
    runs-on: [macos-latest]
    steps:
    - name: Install samba
      run: brew install samba
  build:
    runs-on: ${{ matrix.settings.host }}
    strategy:
      matrix:
        settings:
          - host: ubuntu-24.04
            target: aarch64-unknown-linux-gnu
            runtests: false
          - host: macos-latest
            target: aarch64-apple-darwin
            runtests: true
          - host: macos-latest
            target: x86_64-apple-darwin
            runtests: true
    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v1
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@netapplabs'
    - name: Prepare yarn
      run: yarn install
    - name: Build
      run: yarn build --target ${{ matrix.settings.target }}
    - name: Test
      if: ${{ matrix.settings.runtests }}
      run: yarn test
    - name: Upload node module
      uses: actions/upload-artifact@v4
      with:
        name: smb-js-node-${{ matrix.settings.host }}--${{ matrix.settings.target }}
        path: |
          smb-js.*.node
  publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@netapplabs'
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          pattern: smb-js-node-*
          merge-multiple: true
      - name: Publish Artifacts
        run: npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}