# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main", "npm" ]
  pull_request:
    branches: [ "main" , "npm" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  adeps-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install samba
      run: sudo apt-get -y install samba
  adeps-macos:
    runs-on: [macos-latest macos-latest-large]
    steps:
    - name: Install samba
      run: brew install samba
  build:
    runs-on: ${{ matrix.settings.host }}
    strategy:
      matrix:
        settings:
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu  
          - host: macos-latest
            target: aarch64-apple-darwin
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install non-rust non-node dependencies
      run: ./deps.sh
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@netapplabs'
    - name: Prepare yarn
      run: yarn install
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
    - name: Upload node module
      uses: actions/upload-artifact@v4
      with:
        name: smb-js-node-${{ matrix.settings.host }}
        path: |
          smb-js.*.node
          package.json
          index.*
          indax.*
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: .
          pattern: |
            smb-js-node-*
            package.json
            index.*
            indax.*
          merge-multiple: true  
      - name: Publish Artifacts
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}