# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master", "fridvin*" ]
  pull_request:
    branches: [ "master", "fridvin*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [ 18.x ]
        os: [ macos-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'
        check-latest: true
    - name: Setup SSH
      run: |
        mkdir -p $HOME/.ssh
        echo "${{ secrets.SSH_KEY_FOR_LIBNFS_SYS }}" > $HOME/.ssh/libnfs-sys
        echo "${{ secrets.SSH_KEY_FOR_LIBNFS_RS }}" > $HOME/.ssh/libnfs-rs
        echo "${{ secrets.SSH_KEY_FOR_NFS_RS }}" > $HOME/.ssh/nfs-rs
        chmod 600 $HOME/.ssh/libnfs* $HOME/.ssh/nfs-rs
    - name: Checkout submodules
      run: |
        ln -sf $HOME/.ssh/libnfs-sys $HOME/.ssh/id_rsa
        git clone git@github.com:NetAppLabs/libnfs-sys.git
        ln -sf $HOME/.ssh/libnfs-rs $HOME/.ssh/id_rsa
        git clone git@github.com:NetAppLabs/libnfs-rs.git
        ln -sf $HOME/.ssh/nfs-rs $HOME/.ssh/id_rsa
        git clone git@github.com:NetAppLabs/nfs-rs.git
        rm $HOME/.ssh/id_rsa
    - name: Install non-rust non-node dependencies
      run: ./deps.sh
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Prepare yarn
      run: yarn install --immutable
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
    - name: Upload node module
      uses: actions/upload-artifact@v3
      with:
        name: nfs-js.${{ matrix.os }}-x64-node${{ matrix.node-version }}.node
        path: nfs-js.*.node
